image:
  repository: postgres
  tag: "15.5"

storage:
  size: 5Gi

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "10m"
    memory: "64Mi"

# These are populated during deployment
csi:
  tenantId: ""
  clientId: ""
  keyvaultName: ""

nodeSelector: {}

tolerations: []

affinity: {}
