apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajputganesh217/azure-aks-devsecops-platform.git"
    targetRevision: main
    path: kubernetes/charts/platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajputganesh217/azure-aks-devsecops-platform.git"
    targetRevision: main
    path: kubernetes/charts/platform
    helm:
      parameters:
        - name: backend.ingress.host
          value: "api-qa.microservices.local"
        - name: frontend.ingress.host
          value: "qa.microservices.local"
        - name: postgres.csi.keyvaultName
          value: "qa-devsecops-kv"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: qa
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
