apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajputganesh217/azure-aks-devsecops-platform.git"
    targetRevision: main
    path: kubernetes/charts/platform
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: postgres.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: postgres.csi.tenantId
          value: "${AZURE_TENANT_ID}"
        - name: postgres.csi.keyvaultName
          value: "dev-devsecops-kv"
        - name: backend.image.tag
          value: "backend-dev-latest"
        - name: backend.keyvaultName
          value: "dev-devsecops-kv"
        - name: backend.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: backend.csi.tenantId
          value: "${AZURE_TENANT_ID}"
        - name: frontend.image.tag
          value: "frontend-dev-latest"
        - name: worker.image.tag
          value: "worker-dev-latest"
        - name: worker.keyvaultName
          value: "dev-devsecops-kv"
        - name: worker.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: worker.csi.tenantId
          value: "${AZURE_TENANT_ID}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rajputganesh217/azure-aks-devsecops-platform.git"
    targetRevision: main
    path: kubernetes/charts/platform
    helm:
      parameters:
        - name: backend.ingress.host
          value: "api-qa.microservices.local"
        - name: frontend.ingress.host
          value: "qa.microservices.local"
        - name: postgres.csi.keyvaultName
          value: "qa-devsecops-kv"
        - name: postgres.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: postgres.csi.tenantId
          value: "${AZURE_TENANT_ID}"
        - name: backend.image.tag
          value: "backend-qa-latest"
        - name: backend.keyvaultName
          value: "qa-devsecops-kv"
        - name: backend.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: backend.csi.tenantId
          value: "${AZURE_TENANT_ID}"
        - name: frontend.image.tag
          value: "frontend-qa-latest"
        - name: worker.image.tag
          value: "worker-qa-latest"
        - name: worker.keyvaultName
          value: "qa-devsecops-kv"
        - name: worker.csi.clientId
          value: "${CSI_IDENTITY_CLIENT_ID}"
        - name: worker.csi.tenantId
          value: "${AZURE_TENANT_ID}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
