replicaCount: 1
image:
  repository: mydevopsacr123.azurecr.io/frontend
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: "dev.microservices.local"
  tlsSecretName: microservices-tls-secret

resources:
  limits:
    cpu: "50m"
    memory: "64Mi"
  requests:
    cpu: "10m"
    memory: "32Mi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 70
