apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shoe-frontend
  template:
    metadata:
      labels:
        app: shoe-frontend
    spec:
      serviceAccountName: frontend-sa
      automountServiceAccountToken: false
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /health.html
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.html
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 3
          periodSeconds: 5
