pipeline {
    agent any

    environment {
        TF_DIR = "infra/terraform/env/dev"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/rajputganesh217/azure-aks-devsecops-platform.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([
                    string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'SUB'),
                    string(credentialsId: 'AZURE_TENANT_ID', variable: 'TENANT'),
                    string(credentialsId: 'AZURE_CLIENT_ID', variable: 'CLIENT'),
                    string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'SECRET'),

                    string(credentialsId: 'POSTGRES_DB', variable: 'POSTGRES_DB'),
                    string(credentialsId: 'POSTGRES_USER', variable: 'POSTGRES_USER'),
                    string(credentialsId: 'POSTGRES_PASSWORD', variable: 'POSTGRES_PASSWORD'),
                    string(credentialsId: 'DB_HOST', variable: 'DB_HOST')
                ]) {

                    dir("${TF_DIR}") {

                        sh """
                        terraform plan \
                        -var="subscription_id=$SUB" \
                        -var="tenant_id=$TENANT" \
                        -var="client_id=$CLIENT" \
                        -var="client_secret=$SECRET" \
                        -var="postgres_db=$POSTGRES_DB" \
                        -var="postgres_user=$POSTGRES_USER" \
                        -var="postgres_password=$POSTGRES_PASSWORD" \
                        -var="db_host=$DB_HOST"
                        """
                    }
                }
            }
        }

        stage('Terraform Apply') {

            steps {

                input message: "Approve Infrastructure Creation?"

                withCredentials([
                    string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'SUB'),
                    string(credentialsId: 'AZURE_TENANT_ID', variable: 'TENANT'),
                    string(credentialsId: 'AZURE_CLIENT_ID', variable: 'CLIENT'),
                    string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'SECRET'),

                    string(credentialsId: 'POSTGRES_DB', variable: 'POSTGRES_DB'),
                    string(credentialsId: 'POSTGRES_USER', variable: 'POSTGRES_USER'),
                    string(credentialsId: 'POSTGRES_PASSWORD', variable: 'POSTGRES_PASSWORD'),
                    string(credentialsId: 'DB_HOST', variable: 'DB_HOST')
                ]) {

                    dir("${TF_DIR}") {

                        sh """
                        terraform apply -auto-approve \
                        -var="subscription_id=$SUB" \
                        -var="tenant_id=$TENANT" \
                        -var="client_id=$CLIENT" \
                        -var="client_secret=$SECRET" \
                        -var="postgres_db=$POSTGRES_DB" \
                        -var="postgres_user=$POSTGRES_USER" \
                        -var="postgres_password=$POSTGRES_PASSWORD" \
                        -var="db_host=$DB_HOST"
                        """
                    }
                }
            }
        }

    }
}
