apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoe-frontend
  template:
    metadata:
      labels:
        app: shoe-frontend
    spec:
      containers:
      - name: frontend
        image: "{{IMAGE_TAG}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "20m"
            memory: "64Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.html
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
