apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoe-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: "{{HOSTNAME}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shoe-frontend
            port:
              number: 80
