apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoe-ingress
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/health-probe-path: "/"
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: dev.microservices.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shoe-frontend
            port:
              number: 80
