apiVersion: v1
kind: Service
metadata:
  name: shoe-frontend
  namespace: ${NAMESPACE}
  labels:
    app: shoe-frontend
spec:
  type: ClusterIP
  selector:
    app: shoe-frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
