apiVersion: v2
name: platform
description: DevSecOps Platform - Umbrella Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgres
    version: "0.1.0"
    repository: "file://../postgres"
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: backend
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: frontend
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: worker
