apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: "${CSI_IDENTITY_CLIENT_ID}" 
    keyvaultName: "dev-devsecops-kv"
    objects: |
      array:
        - |
          objectName: POSTGRES-DB
          objectType: secret
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
    tenantId: "${AZURE_TENANT_ID}"
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: POSTGRES-DB
          key: POSTGRES_DB
        - objectName: POSTGRES-USER
          key: POSTGRES_USER
        - objectName: POSTGRES-PASSWORD
          key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:      
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:15.5
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        securityContext:   
          allowPrivilegeEscalation: false
        resources:          
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        livenessProbe:      
          exec:
            command:
              - pg_isready
              - -U
              - "$(POSTGRES_USER)"
              - -d
              - "$(POSTGRES_DB)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:     
          exec:
            command:
              - pg_isready
              - -U
              - "$(POSTGRES_USER)"
              - -d
              - "$(POSTGRES_DB)"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev
spec:
  ports:
  - port: 5432
  selector:
    app: postgres